collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1071845
  brandStrength: 0.4862603
  lightness: 0.6855899
  brandColors:
    - '#8A8B8B'
    - '#4B545B'
    - '#272731'
    - '#0C0D0E'
    - '#D0D0CE'
  rhythmicContrast: 0.09368518
typography_spectrum: 0.8034824
layout_spectrum: 0.6425532
name: Artwork
