layout_spectrum: 0.7749684
typography_spectrum: 0.8034824
color:
  saturation: 0.1071845
  lightness: 0.6855899
  brandStrength: 0.4862603
  rhythmicContrast: 0.09368518
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Artwork
